security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Contractor:
            algorithm: auto

    providers:
        app_contractor_provider:
            entity:
                class: App\Entity\Contractor
                property: login

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_contractor_provider
            user_checker: App\Security\ContractorUserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: login
                password_parameter: password
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/onlyoffice/callback, roles: PUBLIC_ACCESS }
        - { path: ^/onlyoffice/download, roles: PUBLIC_ACCESS }
        - { path: ^/oo/, roles: PUBLIC_ACCESS }
        - { path: ^/files/, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_CONTRACTOR }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
