# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    env(HLK_FILES_DIR): '%kernel.project_dir%/public/files'
    env(ONLYOFFICE_URL): '/oo'
    env(ONLYOFFICE_APP_URL): 'auto'
    env(ONLYOFFICE_JWT_SECRET): ''
    env(ONLYOFFICE_DS_APP_URL): ''
    env(ONLYOFFICE_INTERNAL_URL): ''
    app.dirs.files.local: '%env(resolve:HLK_FILES_DIR)%'
    app.dirs.files.public: '/files'
    onlyoffice.url: '%env(ONLYOFFICE_URL)%'
    onlyoffice.app_url: '%env(ONLYOFFICE_APP_URL)%'
    onlyoffice.jwt_secret: '%env(ONLYOFFICE_JWT_SECRET)%'
    onlyoffice.ds_app_url: '%env(ONLYOFFICE_DS_APP_URL)%'
    onlyoffice.internal_url: '%env(ONLYOFFICE_INTERNAL_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appDirsFilesLocal: '%app.dirs.files.local%'
            $appDirsFilesPublic: '%app.dirs.files.public%'
            $onlyOfficeUrl: '%onlyoffice.url%'
            $onlyOfficeAppUrl: '%onlyoffice.app_url%'
            $onlyOfficeJwtSecret: '%onlyoffice.jwt_secret%'
            $onlyOfficeDsAppUrl: '%onlyoffice.ds_app_url%'
            $onlyOfficeInternalUrl: '%onlyoffice.internal_url%'

    App\:
        resource: '../src/'
